apiVersion: v1
kind: Pod
metadata:
 name: webpod2
 namespace: devproject
 labels:  #to map it with the service
  app: web2
  env: dev2
spec:
  containers:
  - name: webcontainer2
    image: arumugam0911/startup:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: apache
      protocol: TCP
    resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
 name: clusteripservice   #service name (it can be any name)
 namespace: devproject
spec:
 ports:
 - name: apache
   port: 80 #service port
   targetPort: 80 #container port
   protocol: TCP
 selector:     #mapping to pod
   app: web2
   env: dev2