apiVersion: v1
kind: Pod
metadata:
  name: webpod2
  namespace: devproject
  labels:  #to map it with the service
   app: web2
   env: dev2
spec:
  containers:
  - name: webcontainer
    image: arumugam0911/startup:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
      name: apache
    resources:
      limits:
        cpu: 500m
        memory: 400Mi
      requests:
        cpu: 250m
        memory: 100Mi
  restartPolicy: Always
    
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancerservice
  namespace: devproject
spec:
  selector:
    app: web2
    env: dev2
  ports:
  - port: 80 #service port
    targetPort: 80 #container port
    protocol: TCP
    name: apache
  type: LoadBalancer