apiVersion: v1
kind: Pod
metadata:
  name: webpod
  namespace: devproject
  labels:  #to map it with the service
   app: web
   env: dev
spec:
  containers:
  - name: webcontainer
    image: arumugam0911/website:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
      name: apache
    resources:
      limits:
        cpu: 500m
        memory: 400Mi
      requests:
        cpu: 250m
        memory: 100Mi
  restartPolicy: Always
    
---
apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
  namespace: devproject
spec:
  selector:
    app: web
    env: dev
  ports:
  - nodePort: 30002 #node port mention the same in security group
    port: 80 #service port
    targetPort: 80 #container port
    protocol: TCP
    name: apache
  type: NodePort