apiVersion: v1
kind: Pod
metadata:
  name: webpod
  namespace: devproject
spec:
  containers:
  - name: webcontainer
    image: arumugam0911/startup:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: apache
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
         memory: "128Mi"
         cpu: "500m"
  restartPolicy: OnFailure